# team-3-rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: team-3-admin-binding
  namespace: team-3-prod
subjects:
- kind: ServiceAccount
  name: team-3-admin
  namespace: team-3-prod
roleRef:
  kind: Role
  name: namespace-admin
  apiGroup: rbac.authorization.k8s.io
